/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Calculator_Testing;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}



public class HoJoBoRoLo{ 
	public static void main(String args[]){
		System.out.println("Live long KSL");
	}
}

